- name: install pip
  apt:
    name: python3-pip
    state: present

- name: pip install docker-py
  pip:
    name:
      - docker
      - docker-compose
- name: add user ansible in docker group
  user:
    name: jenkins
    groups: docker
    append: yes
  become: true
  
- name: run container
  docker_container:
    name: wartest
    image: "{{ image }}"
    ports: 8081:8080
    state: started
 
